services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - awesomecord

  backend:
    image: ghcr.io/${GH_OWNER}/awesomecord-backend:${TAG}
    env_file:
      - ./Backend/Awesomecord/API/.env.production
    ports:
      - "5000:5000"
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - awesomecord
    volumes:
      - awesomecord_sqlite_data:/app/data

  frontend:
    image: ghcr.io/${GH_OWNER}/awesomecord-frontend:${TAG}
    environment:
      VITE_PUBLIC_API_URL: ${PUBLIC_API_URL}
    ports:
      - "5173:8080"
    depends_on:
      - backend
    networks:
      - awesomecord

volumes:
  minio_data:
  awesomecord_sqlite_data:

networks:
  awesomecord:
    driver: bridge
